version: '3'
services:
  trgger:
    container_name: 'my-trgger'
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8100:8080'
    working_dir: /home/
    command: yarn start
